### ISSUE TITLE
Archive: Настроить резервное копирование данных сервера

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/archive.morevnaproject.org#11]

**Comment by morevnaproject** [comment]
@evgenijkatunov Я настроил резервное копирование файлов с сервера.
Но нужно ещё сделать так, чтобы создавался ежедневный дамп базы данных, чтобы потом этот файл и копировался.

Лучше всего, чтобы дамп делался через специальный контейнер -
```
  mysql-cron-backup-nextcloud:
    container_name: mysql-cron-backup-nextcloud
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    volumes:
      - ./school-backup:/backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=...
      - MYSQL_PASS=...
      - MYSQL_DB=...
      - MAX_BACKUPS=5
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
    restart: unless-stopped
```

Подробности здесь - https://github.com/fradelg/docker-mysql-cron-backup
